# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ebennix <ebennix@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/16 15:35:48 by ebennix           #+#    #+#              #
#    Updated: 2024/01/18 03:54:52 by ebennix          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

EXE := test00

CPP := clang++

CPPFLAGS := -Wall -Wextra -Werror

INC := ICharacter.hpp IMateriaSource.hpp AMateria.hpp \

FILE := main \

SRC := $(FILE:=.cpp)

OBJ := $(SRC:.cpp=.o)

################################################################################ 

all: $(EXE)

$(EXE): $(OBJ)
	$(CPP) $(CPPFLAGS) $(OBJ) -o $(EXE)

%.o: %.cpp $(INC)
	$(CPP) $(CPPFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJ)

fclean: clean
	rm -rf $(EXE)

re: fclean all

################################################################################ 

.PHONY: all clean fclean re